/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        secondary: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#14532d',
        },
      },
      animation: {
        'bounce-slow': 'bounce 3s infinite',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'animate-breathe': 'breathe 4s ease-in-out infinite',
        'animate-roar': 'roar 0.5s ease-in-out',
        'animate-hit': 'hit 0.3s ease-in-out',
        'animate-dodge': 'dodge 0.3s ease-in-out',
        'animate-spin-slow': 'spinSlow 6s linear infinite',
        'animate-victory': 'victory 1s ease-out forwards',
        'animate-float': 'float 6s ease-in-out infinite',
        'animate-shake': 'shake 0.5s ease-in-out',
        'animate-tremor': 'tremor 0.6s ease-in-out',
        'animate-sword-slash': 'swordSlash 0.6s ease-in-out forwards',
        'animate-hp-pulse': 'hpPulse 1s ease-in-out infinite',
        'animate-card-glow': 'cardGlow 3s ease-in-out infinite',
        'animate-card-pop': 'cardPop 0.5s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'animate-particle-float': 'particleFloat 2s ease-in-out forwards',
        'animate-card-shine': 'cardShine 3s ease-in-out infinite',
        'animate-fade-in-up': 'fadeInUp 0.5s ease-out forwards',
        'animate-dungeon-enter': 'dungeonEnter 0.8s ease-out forwards',
      },
    },
  },
  plugins: [],
}
